library home_screen_route_imple.dart;

import 'dart:developer';
import 'dart:io';

import 'package:auto_proof/constants/const_color.dart';
import 'package:auto_proof/constants/const_image.dart';
import 'package:auto_proof/constants/const_route_string.dart';
import 'package:auto_proof/presentation/auth_screens/change_password/change_password_screen_route_imple.dart';
import 'package:auto_proof/presentation/screens/company/company_screen_route_imple.dart';
import 'package:auto_proof/presentation/screens/contact_us/contact_us_screen_route_imple.dart';
import 'package:auto_proof/presentation/screens/notification/notification_screen_route_imple.dart';
import 'package:auto_proof/presentation/screens/personal_information_screens/personal_information_route_imple.dart';
import 'package:auto_proof/presentation/screens/team_View/web_team_profile_screen.dart';
import 'package:auto_proof/utilities/custom_button.dart';
import 'package:auto_proof/utilities/custom_textstyle.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../../../auth/server/default_db/sharedprefs_method.dart';
import '../../../../constants/const_string.dart';
import '../../../../l10n/app_localizations.dart';
import '../../../../responsive.dart';
import '../../../../utilities/custom_widgets.dart';
import '../../../../utilities/profile_image.dart';
import '../../payment/payment_screen_route_imple.dart';
import '../../personal_information_screens/bloc/personal_information_bloc/personal_information_bloc.dart';
import '../../subscription/subscription_screen_route_imple.dart';
import '../../team_View/team_screen_route_imple.dart';
import '../../vehicles_screen/vehicles_screen_route_imple.dart';

part 'home_screen.dart';
part 'dashboard_screen.dart';
part 'profile_screen.dart';
part 'subscription_card_view.dart';
part 'web_insection_screen.dart';
part 'welcome_screen.dart';